### ISSUE TITLE
Kurdebele ogarnąć jak to w EAGLE odpalić

### ISSUE THREAD

**Issue by romanzemela** [matpiwowarski/Embedded-systems#1]

**Comment by romanzemela** [comment]
Albo znaleźć konwerter z PSoC 5LP na Eagle, albo znaleźć biblio do Eagle na obsługę tych plików

**Comment by romanzemela** [comment]
Dobra robota Mateusz Piwowarski.

**Comment by matpiwowarski** [comment]
Dziękuję, pozdrawiam.
